version: "3"

services:
  traefik:
    image: traefik
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/static.toml:/etc/traefik/traefik.toml"
      - "./traefik/dynamic.toml:/etc/traefik/dynamic.toml"

  homer:
    image: "b4bz/homer"
    container_name: "homer"
    labels:
      - "traefik.enable=true"
    volumes:
      - ./homer/:/www/assets
