version: "3"

services:
  traefik:
    image: traefik:v2.11
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/static.toml:/etc/traefik/traefik.toml"
      - "./traefik/dynamic.toml:/etc/traefik/dynamic.toml"

  whoami:
    image: "traefik/whoami"
    container_name: "simple_service"
    labels:
      - "traefik.enable=true"
