[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
    level = "DEBUG"

[entryPoints]
    [entryPoints.web80]
        address = ":80"
    [entryPoints.web443]
        address = ":443"

[providers]
    [providers.docker]
        exposedByDefault = false
    [providers.file]
        filename = "/etc/traefik/dynamic.toml"

[api]
    insecure = true
    dashboard = true
